# Generated by Django 5.0.3 on 2024-03-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
