# Generated by Django 5.0 on 2024-02-22 16:05

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersauth', '0004_alter_customerprofile_user_alter_managerdatail_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('image', models.ImageField(upload_to='category', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='HotelLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_location_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', editable=False, length=8, max_length=20, prefix='hot', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_location/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', length=8, max_length=20, prefix='hot', unique=True)),
                ('paid_status', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, default=70.9, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('book_status', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('coupon', 'Coupon')], default='process', max_length=200)),
                ('invoice_no', models.CharField(default='No2304', max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usersauth.customer')),
            ],
            options={
                'verbose_name_plural': 'Book Orders',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', editable=False, length=8, max_length=20, prefix='fac', unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersauth.manager', verbose_name='Managers')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', length=8, max_length=20, prefix='hot', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=400, verbose_name='address')),
                ('state', models.CharField(max_length=255)),
                ('images', models.ImageField(default='product.jpg', upload_to='hotel-images')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('specifications', models.TextField(max_length=200)),
                ('hotel_status', models.CharField(choices=[('draft', 'Draft'), ('disable', 'Disable'), ('reject', 'Reject'), ('in_review', 'In Review'), ('approved', 'Approved')], default='in_review', max_length=200)),
                ('features', models.BooleanField(default=False, verbose_name='features')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersauth.manager', verbose_name='owner')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotellocation')),
            ],
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewid', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', length=8, max_length=20, prefix='re', unique=True)),
                ('review', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(1, '⭐☆☆☆☆'), (2, '⭐⭐☆☆☆'), (3, '⭐⭐⭐☆☆'), (4, '⭐⭐⭐⭐☆'), (5, '⭐⭐⭐⭐⭐')], default=1)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to='hotels.hotel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usersauth.customer')),
            ],
            options={
                'verbose_name_plural': 'Hotel Reviews',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', editable=False, length=8, max_length=20, prefix='room', unique=True)),
                ('room_no', models.IntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, default=90.93, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('available_rooms', models.CharField(max_length=200)),
                ('room_specification', models.TextField()),
                ('images', models.ImageField(default='product.jpg', upload_to='room-images')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('facilities', models.ManyToManyField(related_name='rooms', to='hotels.facility', verbose_name='facilities')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='product.jpg', upload_to='room-images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='hotels.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', editable=False, length=8, max_length=20, prefix='room', unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersauth.manager', verbose_name='Managers')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.roomtype'),
        ),
    ]
