# Generated by Django 5.0 on 2024-02-22 18:24

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='asd23', editable=False, length=8, max_length=20, prefix='hot', unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotles_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ahel203', editable=False, length=8, max_length=20, prefix='hot', unique=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020d', editable=False, length=8, max_length=20, prefix='fac', unique=True),
        ),
        migrations.AlterField(
            model_name='hotellocation',
            name='hotel_location_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='hoteloc23', editable=False, length=8, max_length=20, prefix='hotl', unique=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='rotre34', editable=False, length=8, max_length=20, prefix='room', unique=True),
        ),
    ]
