# Generated by Django 5.0.3 on 2024-05-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="id",
        ),
        migrations.AddField(
            model_name="image",
            name="url",
            field=models.URLField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
