# Generated by Django 5.0 on 2024-02-19 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsUsermanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='username')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='phone number')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('jsusermanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('otp', models.CharField(blank=True, max_length=6, null=True, verbose_name='OTP')),
            ],
            options={
                'abstract': False,
            },
            bases=('usersauth.jsusermanager',),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('jsusermanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_manager', models.BooleanField(default=False, verbose_name='manager status')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='phone verified')),
                ('otp', models.CharField(blank=True, max_length=6, null=True, verbose_name='OTP')),
            ],
            options={
                'abstract': False,
            },
            bases=('usersauth.jsusermanager',),
        ),
    ]
