# Generated by Django 4.0 on 2024-06-17 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='username')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='phone number')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('auth_user_provider', models.CharField(default='email', max_length=300)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usersauth.user')),
                ('customerid', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', length=8, max_length=20, prefix='cus', unique=True)),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('otp', models.CharField(blank=True, max_length=6, null=True, verbose_name='OTP')),
            ],
            options={
                'abstract': False,
            },
            bases=('usersauth.user',),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usersauth.user')),
                ('managerid', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', length=8, max_length=20, prefix='mgt', unique=True)),
                ('is_manager', models.BooleanField(default=False, verbose_name='manager status')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='phone verified')),
                ('otp', models.CharField(blank=True, max_length=6, null=True, verbose_name='OTP')),
            ],
            options={
                'abstract': False,
            },
            bases=('usersauth.user',),
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faceid_enable', models.BooleanField(default=False)),
                ('enable_auth_login', models.BooleanField(default=False)),
                ('notifcation', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersauth.customer', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerDatail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerprofileid', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', length=8, max_length=20, prefix='mgt', unique=True)),
                ('city', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('Company_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='manager_profiles/')),
                ('Company_status', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregisterd')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='usersauth.manager')),
            ],
            options={
                'verbose_name': 'ManagerDatail',
                'verbose_name_plural': 'ManagerDatails',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerprofileid', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', length=8, max_length=20, prefix='cus', unique=True)),
                ('fullname', models.CharField(max_length=300)),
                ('Location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='manager_profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='usersauth.customer')),
            ],
        ),
    ]
