# Generated by Django 5.0 on 2024-02-19 18:00

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faceid', models.BooleanField(default=False)),
                ('Rememberme', models.BooleanField(default=False)),
                ('Touchid', models.BooleanField(default=False)),
                ('logincode', models.BooleanField(default=False)),
                ('notifcation', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customerid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', length=8, max_length=20, prefix='cus', unique=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='managerid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', length=8, max_length=20, prefix='mgt', unique=True),
        ),
        migrations.CreateModel(
            name='CustomerDatails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerprofileid', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', length=8, max_length=20, prefix='prof', unique=True)),
                ('city', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('Company_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='manager_profiles/')),
                ('Company_status', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregisterd')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usersauth.manager')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerprofileid', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', length=8, max_length=20, prefix='prof', unique=True)),
                ('fullname', models.CharField(max_length=300)),
                ('Location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='manager_profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usersauth.customer')),
            ],
        ),
    ]
