# Generated by Django 4.0 on 2024-06-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='olisa', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='olisa', max_length=200),
        ),
    ]
