# Generated by Django 5.0 on 2024-02-19 18:16

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersauth', '0002_usersetting_customer_customerid_manager_managerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='customerprofileid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', length=8, max_length=20, prefix='cus', unique=True),
        ),
        migrations.CreateModel(
            name='ManagerDatail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerprofileid', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', length=8, max_length=20, prefix='mgt', unique=True)),
                ('city', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('Company_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='manager_profiles/')),
                ('Company_status', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregisterd')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usersauth.manager')),
            ],
            options={
                'verbose_name': 'ManagerDatail',
                'verbose_name_plural': 'ManagerDatails',
            },
        ),
        migrations.DeleteModel(
            name='CustomerDatails',
        ),
    ]
