# Generated by Django 5.0.3 on 2024-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersauth', '0002_customuser_is_active_customuser_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_vendor',
            field=models.BooleanField(default=False, verbose_name='vendor'),
        ),
    ]
