# Generated by Django 4.0 on 2024-06-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersauth', '0003_alter_customer_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='fullname',
        ),
        migrations.AddField(
            model_name='customer',
            name='otp_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='otp_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
