# Generated by Django 5.0.3 on 2024-04-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersauth', '0003_alter_user_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='otp expiry'),
        ),
    ]
