# Generated by Django 5.0 on 2024-02-22 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersauth', '0003_alter_customerprofile_customerprofileid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='usersauth.customer'),
        ),
        migrations.AlterField(
            model_name='managerdatail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='usersauth.manager'),
        ),
    ]
