# Generated by Django 4.2.7 on 2024-06-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersauth', '0004_remove_customerprofile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
