# Generated by Django 5.0 on 2024-02-22 16:05

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', editable=False, length=8, max_length=20, prefix='bo', unique=True)),
                ('booking_status', models.CharField(choices=[('A', 'Availed'), ('B', 'Booked'), ('C1', 'Cancelled by user'), ('C2', 'Cancelled by hotel')], max_length=2)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('total_guests', models.PositiveIntegerField(default=0)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('coupon', models.CharField(max_length=200, verbose_name='coupon')),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('booking_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reservation_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcd2020', editable=False, length=8, max_length=20, prefix='room', unique=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('num_adults', models.PositiveIntegerField(default=1)),
                ('num_children', models.PositiveIntegerField(default=0)),
                ('reservation_code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
