# Generated by Django 5.0.3 on 2024-04-27 03:59

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "hotel_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvwxyz0123456789",
                        editable=False,
                        length=22,
                        max_length=20,
                        prefix="hotl-",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("featured_image", models.URLField()),
                ("facilities", models.JSONField(blank=True, null=True)),
                ("images", models.JSONField(blank=True, null=True)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("registration_number", models.CharField(max_length=255, unique=True)),
                ("registration_status", models.BooleanField(default=True)),
                ("date_registered", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "hotel",
                "verbose_name_plural": "hotels",
            },
        ),
        migrations.CreateModel(
            name="HotelReview",
            fields=[
                (
                    "review_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvwxyz0123456789",
                        editable=False,
                        length=22,
                        max_length=20,
                        prefix="revw-",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("rating", models.PositiveIntegerField()),
                ("review", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="hotel.hotel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "hotel review",
                "verbose_name_plural": "hotel reviews",
            },
        ),
        migrations.CreateModel(
            name="HotelRoom",
            fields=[
                (
                    "room_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvwxyz0123456789",
                        editable=False,
                        length=22,
                        max_length=20,
                        prefix="room-",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.URLField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_guests", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hotel.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "hotel room",
                "verbose_name_plural": "hotel rooms",
            },
        ),
        migrations.CreateModel(
            name="HotelBooking",
            fields=[
                (
                    "booking_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvwxyz0123456789",
                        editable=False,
                        length=22,
                        max_length=20,
                        prefix="book-",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("check_in", models.DateTimeField()),
                ("check_out", models.DateTimeField()),
                ("guests", models.PositiveIntegerField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_booked", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="hotel.hotelroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "hotel booking",
                "verbose_name_plural": "hotel bookings",
            },
        ),
    ]
