# Generated by Django 5.0.3 on 2024-05-01 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
        ("image", "0002_remove_image_id_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="featured_image",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="featured_image",
                to="image.image",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
