# Generated by Django 5.0.3 on 2024-04-08 05:53

import django.utils.timezone
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', editable=False, length=22, max_length=20, prefix='usr-', primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=50, null=True, verbose_name='first name')),
                ('lastname', models.CharField(max_length=50, null=True, verbose_name='last name')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(max_length=15, null=True, unique=True, verbose_name='phone number')),
                ('dob', models.DateField(null=True, verbose_name='date of birth')),
                ('is_vendor', models.BooleanField(default=True, verbose_name='vendor')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('otp', models.CharField(max_length=6, null=True, verbose_name='otp')),
                ('otp_expiry', models.DateTimeField(null=True, verbose_name='otp expiry')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
