# Generated by Django 5.0.3 on 2024-04-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersauth', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_expiry',
            field=models.DateTimeField(null=True, verbose_name='otp expiry'),
        ),
    ]
