# Generated by Django 5.0.3 on 2024-04-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_email_verified_user_phone_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_vendor",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="reset_password_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="verification_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
