# Generated by Django 5.0.3 on 2024-04-28 15:13

import datetime
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_is_vendor_alter_user_reset_password_otp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResetPassword",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvwxyz0123456789",
                        editable=False,
                        length=22,
                        max_length=24,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "expiration_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 4, 28, 15, 18, 33, 58204, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "reset_password",
            },
        ),
    ]
