# Generated by Django 5.0.3 on 2024-04-28 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_resetpassword"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resetpassword",
            name="date_updated",
        ),
        migrations.AddField(
            model_name="resetpassword",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="resetpassword",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 28, 15, 37, 48, 568851, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
