# Generated by Django 5.0.3 on 2024-04-29 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_resetpassword_date_updated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resetpassword",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="resetpassword",
            name="id",
        ),
        migrations.AddField(
            model_name="resetpassword",
            name="reset_password_token",
            field=models.CharField(default=2354, max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resetpassword",
            name="expiration_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="resetpassword",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
