# Generated by Django 5.0.3 on 2024-03-27 01:37

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='max_guests',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', editable=False, length=8, max_length=20, prefix='hotl-', unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='registration_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='registration_status',
            field=models.BooleanField(default=True),
        ),
    ]
