# Generated by Django 5.0.3 on 2024-03-27 01:40

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_max_guests_alter_hotel_hotel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='id',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', editable=False, length=8, max_length=20, prefix='hotl-', primary_key=True, serialize=False, unique=True),
        ),
    ]
