# Generated by Django 5.0.3 on 2024-03-27 01:41

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_hotel_id_alter_hotel_hotel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', editable=False, length=12, max_length=20, prefix='hotl-', primary_key=True, serialize=False, unique=True),
        ),
    ]
