# Generated by Django 5.0.3 on 2024-03-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_description_hotel_featured_image_hotel_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
