# Generated by Django 5.0.3 on 2024-03-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_hotel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rooms',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
